export const Product = [
  {
    id: 1,
    SupplierName: "Fresh Group",
    ProductName: "Nokia",
    ProductCode: "Pr-1",
    Brand: "Nokia",
    Category: "Electronics",
    SubCategory: "Mobile",
    Generic: "550A",
    ProductUnit: "Piece",
    ProductGrade: "A",
    ProductDescription: "Nokia is brand phone",
    ProductImage:
      "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg",
    PurchasePrice: 1200,
    SalesPrice: 1300,
    AlertQuantity: 4,
    ReferenceNo: "A12",
    Discount: 0,
    OpeningQuantity: 12,
    SKU: 12345,
    BoxQuantity: 1,
  },
  {
    id: 2,
    SupplierName: "Tech Solutions",
    ProductName: "Samsung Galaxy",
    ProductCode: "Pr-2",
    Brand: "Samsung",
    Category: "Electronics",
    SubCategory: "Mobile",
    Generic: "A54",
    ProductUnit: "Piece",
    ProductGrade: "A+",
    ProductDescription: "Samsung Galaxy smartphone",
    ProductImage: "",
    PurchasePrice: 25000,
    SalesPrice: 28000,
    AlertQuantity: 5,
    ReferenceNo: "B23",
    Discount: 5,
    OpeningQuantity: 25,
    SKU: 12346,
    BoxQuantity: 1,
  },
  {
    id: 3,
    SupplierName: "Home Essentials",
    ProductName: "Sony Bravia",
    ProductCode: "Pr-3",
    Brand: "Sony",
    Category: "Electronics",
    SubCategory: "TV",
    Generic: "X90K",
    ProductUnit: "Piece",
    ProductGrade: "A",
    ProductDescription: "55 inch 4K Smart TV",
    ProductImage: "",
    PurchasePrice: 55000,
    SalesPrice: 62000,
    AlertQuantity: 3,
    ReferenceNo: "C45",
    Discount: 10,
    OpeningQuantity: 8,
    SKU: 12347,
    BoxQuantity: 1,
  },
  {
    id: 4,
    SupplierName: "Office Depot",
    ProductName: "HP LaserJet",
    ProductCode: "Pr-4",
    Brand: "HP",
    Category: "Electronics",
    SubCategory: "Printer",
    Generic: "M404dn",
    ProductUnit: "Piece",
    ProductGrade: "B+",
    ProductDescription: "Monochrome laser printer",
    ProductImage: "",
    PurchasePrice: 18500,
    SalesPrice: 21000,
    AlertQuantity: 2,
    ReferenceNo: "D67",
    Discount: 0,
    OpeningQuantity: 6,
    SKU: 12348,
    BoxQuantity: 1,
  },
  {
    id: 5,
    SupplierName: "Fresh Group",
    ProductName: "iPhone 15",
    ProductCode: "Pr-5",
    Brand: "Apple",
    Category: "Electronics",
    SubCategory: "Mobile",
    Generic: "A2849",
    ProductUnit: "Piece",
    ProductGrade: "A++",
    ProductDescription: "Apple iPhone 15 Pro Max",
    ProductImage: "",
    PurchasePrice: 110000,
    SalesPrice: 125000,
    AlertQuantity: 4,
    ReferenceNo: "E89",
    Discount: 3,
    OpeningQuantity: 15,
    SKU: 12349,
    BoxQuantity: 1,
  },
  {
    id: 6,
    SupplierName: "Tech Solutions",
    ProductName: "Dell XPS",
    ProductCode: "Pr-6",
    Brand: "Dell",
    Category: "Electronics",
    SubCategory: "Laptop",
    Generic: "XPS15",
    ProductUnit: "Piece",
    ProductGrade: "A",
    ProductDescription: "15 inch ultrabook laptop",
    ProductImage: "",
    PurchasePrice: 95000,
    SalesPrice: 105000,
    AlertQuantity: 3,
    ReferenceNo: "F12",
    Discount: 5,
    OpeningQuantity: 10,
    SKU: 12350,
    BoxQuantity: 1,
  },
  {
    id: 7,
    SupplierName: "Home Essentials",
    ProductName: "Whirlpool Fridge",
    ProductCode: "Pr-7",
    Brand: "Whirlpool",
    Category: "Appliances",
    SubCategory: "Refrigerator",
    Generic: "WDE245",
    ProductUnit: "Piece",
    ProductGrade: "A",
    ProductDescription: "Double door refrigerator 235L",
    ProductImage: "",
    PurchasePrice: 32000,
    SalesPrice: 36000,
    AlertQuantity: 2,
    ReferenceNo: "G34",
    Discount: 8,
    OpeningQuantity: 5,
    SKU: 12351,
    BoxQuantity: 1,
  },
  {
    id: 8,
    SupplierName: "Office Depot",
    ProductName: "Logitech Mouse",
    ProductCode: "Pr-8",
    Brand: "Logitech",
    Category: "Accessories",
    SubCategory: "Mouse",
    Generic: "MX Master 3",
    ProductUnit: "Piece",
    ProductGrade: "A",
    ProductDescription: "Wireless bluetooth mouse",
    ProductImage: "",
    PurchasePrice: 4500,
    SalesPrice: 5500,
    AlertQuantity: 10,
    ReferenceNo: "H56",
    Discount: 0,
    OpeningQuantity: 40,
    SKU: 12352,
    BoxQuantity: 20,
  },
  {
    id: 9,
    SupplierName: "Fresh Group",
    ProductName: "Canon Camera",
    ProductCode: "Pr-9",
    Brand: "Canon",
    Category: "Electronics",
    SubCategory: "Camera",
    Generic: "EOS R50",
    ProductUnit: "Piece",
    ProductGrade: "A",
    ProductDescription: "Mirrorless camera 24MP",
    ProductImage: "",
    PurchasePrice: 58000,
    SalesPrice: 65000,
    AlertQuantity: 3,
    ReferenceNo: "I78",
    Discount: 7,
    OpeningQuantity: 7,
    SKU: 12353,
    BoxQuantity: 1,
  },
  {
    id: 10,
    SupplierName: "Tech Solutions",
    ProductName: "JBL Speaker",
    ProductCode: "Pr-10",
    Brand: "JBL",
    Category: "Audio",
    SubCategory: "Speaker",
    Generic: "Charge 5",
    ProductUnit: "Piece",
    ProductGrade: "B+",
    ProductDescription: "Portable bluetooth speaker",
    ProductImage: "",
    PurchasePrice: 8500,
    SalesPrice: 10500,
    AlertQuantity: 6,
    ReferenceNo: "J90",
    Discount: 5,
    OpeningQuantity: 18,
    SKU: 12354,
    BoxQuantity: 6,
  },
];

export const ProductBrand = [
  {
    id: 1,
    brandName: "X-Monica",
    brandCode: "001",
    status: true,
  },
  {
    id: 2,
    brandName: "TechFlow",
    brandCode: "002",
    status: true,
  },
  {
    id: 3,
    brandName: "AuraBeam",
    brandCode: "003",
    status: false,
  },
  {
    id: 4,
    brandName: "ZenithCore",
    brandCode: "004",
    status: true,
  },
  {
    id: 5,
    brandName: "NexaPro",
    brandCode: "005",
    status: false,
  },
  {
    id: 6,
    brandName: "Veloxis",
    brandCode: "006",
    status: true,
  },
];

export const ProductGrade = [
  {
    id: "1",
    grade: "A",
    description: "A Grade QUality",
    status: true,
  },
  {
    id: "2",
    grade: "B",
    description: "B Grade QUality",
    status: true,
  },
  {
    id: "3",
    grade: "C",
    description: "C Grade QUality",
    status: false,
  },
];

export const ProductUnit = [
  { id: 1, unitName: "Piece", description: "Individual item", status: true },
  { id: 2, unitName: "Kilogram", description: "Weight (kg)", status: true },
  { id: 3, unitName: "Liter", description: "Volume (L)", status: true },
  { id: 4, unitName: "Meter", description: "Length (m)", status: true },
  { id: 5, unitName: "Dozen", description: "12 pieces", status: true },
  { id: 6, unitName: "Pack", description: "Pre-packaged", status: true },
  { id: 7, unitName: "Box", description: "Box container", status: true },
  { id: 8, unitName: "Set", description: "Group of items", status: true },
  { id: 9, unitName: "Pair", description: "2 pieces", status: true },
  { id: 10, unitName: "Gram", description: "Small weight (g)", status: true },
  {
    id: 11,
    unitName: "Milliliter",
    description: "Small volume (ml)",
    status: true,
  },
  {
    id: 12,
    unitName: "Centimeter",
    description: "Small length (cm)",
    status: true,
  },
  { id: 13, unitName: "Hour", description: "Service hour", status: true },
  { id: 14, unitName: "Roll", description: "Rolled product", status: true },
  { id: 15, unitName: "Bottle", description: "Bottled item", status: true },
];
